/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ListingStorage } from "./ListingStorage";
export type { SimpleAuction } from "./SimpleAuction";
