/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { SimpleAuction } from "./SimpleAuction";
export * as factories from "./factories";
export { Auction__factory } from "./factories/Auction__factory";
export { SimpleAuction__factory } from "./factories/SimpleAuction__factory";
